login: ""  # Ваш логин он ВКонтакте
password: ""  # Ваш пароль он ВКонтакте
token: "vk1.a.hQN1IRSc4dQvDzDfxYa8QrJg6Fp5sdPipOP8HkPSHX1oQzpSGgAQSz8LB1_GjIc8zMCpCJ7sMrOu-cGaaTSFiFxLbu4JTBYC9MffO3fNwhJMmi6S4zrxl1qcNva1qj3mnTpeZmHE6awyCRcc5WQVVEpLUvnNFpwKLsfKPH7cDLHPXkvCJykpl-BHq7WJcEh96VWBnQPVmcl3XqQD8Zfc_w"  # Ваш токен (для скачивания фото участников беседы)